name: GitHub NOTAMS for GVSC Discord Webhook
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  post-notam-discord:
    name: Post NOTAM to Discord
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'notam')) }}
    uses: cl8dep/action-discord@v0.1
    with:
      webhook: ${{ secrets.DSCRD_NOTAM_WBHOOK }}
      message: ${{ github.event.pull_request.title }}
